<?php
/**
 * Implements hook_init().
 */
function fitvids_init() {
  // Include the FitVids.js plugin
  drupal_add_js(drupal_get_path('module', 'fitvids') . '/jquery.fitvids.js');

  // User should be able to choose which container to call this on
  // TODO create an options page where the user can enter a list of jquery selectors
  drupal_add_js('jQuery(".region").fitVids();',
    array('type' => 'inline', 'scope' => 'footer', 'weight' => 5)
  );
}
